# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Q5NJCYOEudmSbjxvJXbeZC-29pZyJM1M
"""

#Import dari Library Numpy
import numpy as np

#Input pertama Program 10 batch dengan 6 layer
inputs1 = [[2.03, 1.68, 2.41, 2.20, 2.71, 0.82, 2.43, 0.76, 2.31, 0.93],
		     [2.40, 1.75, 0.37, 1.60, 2.26, 1.45, 2.96, 0.73, 1.57, 0.92],
		     [1.51, 2.39, 0.97, 1.90, 0.91, 1.49, 1.30, 2.58, 0.68, 0.27],
         [2.74, 0.11, 0.70, 1.61, 2.97, 1.16, 1.05, 2.33, 0.51, 1.08],
         [1.19, 0.18, 3.00, 0.96, 0.64, 2.91, 1.93, 1.50, 1.29, 1.94],
         [1.18, 1.43, 1.33, 2.90, 2.25, 1.15, 0.56, 2.46, 1.25, 2.66]]

#Weight pertama dari program 5 Batch
weights1 = [[2.71, 0.40, 0.04, 0.55, 2.74, 0.90, 0.86, 1.35, 3.08, 2.20],
	         [2.43, 0.48, 0.61, 1.04, 2.64, 1.89, 1.68, 1.74, 1.03, 2.28],
		       [1.80, 0.43, 2.39, 1.92, 2.18, 2.19, 2.71, 2.59, 0.39, 1.61],
           [1.46, 0.49, 1.74, 2.20, 1.86, 1.68, -3.92, 1.33, 3.23, 3.22],
           [0.51, 2.11, 1.22, 1.65, 1.06, 2.67, 1.49, 1.63, 2.90, -0.38,]]

#Bias pertama program tersebut         
biases1 = [1.98, 2.86, 1.95, 0.62, 2.28]

#Weight kedua dari program
weights2 = [[-3.93, 0.14, 0.86, 0.48, -1.27],
            [0.36, 3.30, 3.65, 0.26, -2.60],
            [-0.12, -0.29, -0.73, 1.70, -0.01]]

#Bias kedua dari program
biases2 = [-3.83, -1.16,-2.86]

#deklarasi dari bentuk program untuk menghitung layer 1
layer1_outputs = np.dot(inputs1, np.array(weights1).T) + biases1 

#deklarasi dari bentuk program untuk menghitung layer 2 dari hasil layer 1
layer2_outputs = np.dot(layer1_outputs, np.array(weights2).T) + biases2

#untuk mencetak hasil program
print(layer2_outputs)

"""# Bagian Baru"""

